<font color="blue">

### Data Science Academy

### Big Data Real-Time Analytics com Python e Spark

### Capítulo 2 

### Exercício </font>

Dados obtidos do Portal Brasileiro de Dados Abertos: http://dados.gov.br/dataset/cidades-digitais

O projeto Cidades Digitais foi planejado para modernizar a gestçao e ampliar o acesso ao serviço público, bem como promover o desenvolvimento dos municípios brasileiros através da tecnologia.

### Group By e Reshape

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html <br/>

https://pandas.pydata.org/pandas-docs/stable/user_guide/reshaping.html

In [1]:
import numpy as np
import pandas as pd

In [2]:
cidadesDigitais = pd.read_csv('cidades_digitais.csv', sep=';', encoding ='latin-1')

In [3]:
cidadesDigitais.head()

,UF,CIDADE,IBGE,POPULAÇÃO,VALOR_TOTAL_PREVISTO,STATUS,PONTOS_ATENDIDOS,VALOR_INVESTIDO
0,AC,Tarauacá,1200609,38819,"484.547,53",Sem Previsão,8,0
1,AL,Delmiro Gouveia,2702405,51997,"1.169.381,70",Sem Previsão,43,0
2,AL,Estrela de Alagoas,2702553,18306,"527.206,83",Sem Previsão,39,0
3,AM,Autazes,1300300,37033,"1.171.151,92",Sem Previsão,51,0
4,AM,Benjamin Constant,1300607,39484,"844.586,48",Sem Previsão,12,0

In [4]:
cidadesDigitais.count()

UF                      338
CIDADE                  338
IBGE                    338
POPULAÇÃO               338
VALOR_TOTAL_PREVISTO    338
STATUS                  338
PONTOS_ATENDIDOS        338
VALOR_INVESTIDO         338
dtype: int64

In [5]:
del cidadesDigitais['IBGE']

In [6]:
#Aplicando Group By
cidadesUF_1 = cidadesDigitais.groupby("UF")

In [7]:
type(cidadesUF_1)

pandas.core.groupby.generic.DataFrameGroupBy

In [8]:
cidadesUF_1.head()

,UF,CIDADE,POPULAÇÃO,VALOR_TOTAL_PREVISTO,STATUS,PONTOS_ATENDIDOS,VALOR_INVESTIDO
0,AC,Tarauacá,38819,"484.547,53",Sem Previsão,8,0
1,AL,Delmiro Gouveia,51997,"1.169.381,70",Sem Previsão,43,0
2,AL,Estrela de Alagoas,18306,"527.206,83",Sem Previsão,39,0
3,AM,Autazes,37033,"1.171.151,92",Sem Previsão,51,0
4,AM,Benjamin Constant,39484,"844.586,48",Sem Previsão,12,0
...,...,...,...,...,...,...,...
303,SP,Cachoeira Paulista,32294,"935.119,68",Sem Previsão,27,0
334,TO,Paraíso do Tocantins,49076,"1.872.693,90",Sem Previsão,49,0
335,TO,Ponte Alta do Bom Jesus,4649,"251.266,44",Sem Previsão,9,"23.969,90"
336,TO,Porto Nacional,52182,"1.101.168,76",Sem Previsão,61,0
337,TO,São Miguel do Tocantins,11597,"592.549,70",Sem Previsão,20,0

In [9]:
cidadesUF_1.groups

{'AC': Int64Index([0], dtype='int64'),
 'AL': Int64Index([1, 2], dtype='int64'),
 'AM': Int64Index([3, 4, 5, 6, 7, 8, 9, 10, 11], dtype='int64'),
 'AP': Int64Index([12, 13, 14, 15, 16, 17], dtype='int64'),
 'BA': Int64Index([18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
             35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
            dtype='int64'),
 'CE': Int64Index([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
             68, 69, 70, 71, 72, 73, 74, 75, 76],
            dtype='int64'),
 'DF': Int64Index([77], dtype='int64'),
 'ES': Int64Index([78, 79, 80, 81], dtype='int64'),
 'GO': Int64Index([82, 83, 84, 85, 86, 87, 88, 89, 90, 91], dtype='int64'),
 'MA': Int64Index([ 92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
             105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117],
            dtype='int64'),
 'MG': Int64Index([118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
             131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
             144, 145],
            dtype='int64'),
 'MS': Int64Index([146, 147, 148], dtype='int64'),
 'MT': Int64Index([149, 150, 151, 152], dtype='int64'),
 'PA': Int64Index([153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
             166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176],
            dtype='int64'),
 'PB': Int64Index([177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189,
             190, 191, 192, 193, 194],
            dtype='int64'),
 'PE': Int64Index([195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
             208, 209, 210],
            dtype='int64'),
 'PI': Int64Index([211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223,
             224, 225, 226, 227, 228],
            dtype='int64'),
 'PR': Int64Index([229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241,
             242, 243, 244, 245],
            dtype='int64'),
 'RJ': Int64Index([246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258,
             259, 260],
            dtype='int64'),
 'RN': Int64Index([261, 262, 263, 264, 265, 266, 267, 268, 269], dtype='int64'),
 'RO': Int64Index([270, 271], dtype='int64'),
 'RR': Int64Index([272], dtype='int64'),
 'RS': Int64Index([273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
             286, 287, 288],
            dtype='int64'),
 'SC': Int64Index([289, 290, 291, 292, 293, 294], dtype='int64'),
 'SE': Int64Index([295, 296, 297, 298], dtype='int64'),
 'SP': Int64Index([299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
             312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
             325, 326, 327, 328, 329, 330, 331, 332, 333],
            dtype='int64'),
 'TO': Int64Index([334, 335, 336, 337], dtype='int64')}

In [11]:
#Quantidade de grupos
len(cidadesUF_1.groups)

27

In [12]:
ordenaUF = cidadesUF_1.size()

In [13]:
type(ordenaUF)

pandas.core.series.Series

In [14]:
# Ordena os grupos por ordem decrescente.
ordenaUF.sort_values(ascending=False)

UF
SP    35
BA    33
MG    28
MA    26
CE    26
PA    24
PI    18
PB    18
PR    17
PE    16
RS    16
RJ    15
GO    10
RN     9
AM     9
AP     6
SC     6
ES     4
TO     4
MT     4
SE     4
MS     3
RO     2
AL     2
DF     1
RR     1
AC     1
dtype: int64

In [15]:
cidadesUF_2 = cidadesDigitais.groupby(['UF', 'STATUS'])

In [16]:
type(cidadesUF_2)

pandas.core.groupby.generic.DataFrameGroupBy

In [17]:
#Total agrupado
cidadesUF_2.size()

UF  STATUS
AC  Sem Previsão     1
AL  Sem Previsão     2
AM  Concluída        3
    Sem Previsão     6
AP  Concluída        1
    Sem Previsão     5
BA  Concluída        9
    Sem Previsão    24
CE  Concluída       11
    Sem Previsão    15
DF  Concluída        1
ES  Sem Previsão     4
GO  Sem Previsão    10
MA  Concluída        1
    Sem Previsão    25
MG  Concluída        2
    Em andamento     1
    Sem Previsão    25
MS  Sem Previsão     3
MT  Sem Previsão     4
PA  Concluída        9
    Sem Previsão    15
PB  Concluída        6
    Em andamento     3
    Sem Previsão     9
PE  Concluída        1
    Sem Previsão    15
PI  Concluída        3
    Sem Previsão    15
PR  Concluída        7
    Em andamento     1
    Sem Previsão     9
RJ  Concluída        1
    Em andamento     2
    Sem Previsão    12
RN  Concluída        1
    Sem Previsão     8
RO  Sem Previsão     2
RR  Sem Previsão     1
RS  Concluída        4
    Em andamento     2
    Sem Previsão    10
SC  Concluída        1
    Sem Previsão     5
SE  Sem Previsão     4
SP  Concluída        8
    Em andamento     2
    Sem Previsão    25
TO  Sem Previsão     4
dtype: int64

In [18]:
cidadesDigitais.head()

,UF,CIDADE,POPULAÇÃO,VALOR_TOTAL_PREVISTO,STATUS,PONTOS_ATENDIDOS,VALOR_INVESTIDO
0,AC,Tarauacá,38819,"484.547,53",Sem Previsão,8,0
1,AL,Delmiro Gouveia,51997,"1.169.381,70",Sem Previsão,43,0
2,AL,Estrela de Alagoas,18306,"527.206,83",Sem Previsão,39,0
3,AM,Autazes,37033,"1.171.151,92",Sem Previsão,51,0
4,AM,Benjamin Constant,39484,"844.586,48",Sem Previsão,12,0

In [19]:
cidadesUF_3 = cidadesDigitais.set_index('STATUS')

In [20]:
type(cidadesUF_3)

pandas.core.frame.DataFrame

In [21]:
#Aplicando Group By
cidadesUF_3 = cidadesUF_3.groupby('STATUS')

In [22]:
cidadesUF_3.head()

,UF,CIDADE,POPULAÇÃO,VALOR_TOTAL_PREVISTO,PONTOS_ATENDIDOS,VALOR_INVESTIDO
STATUS,,,,,,
Sem Previsão,AC,Tarauacá,38819,"484.547,53",8,0
Sem Previsão,AL,Delmiro Gouveia,51997,"1.169.381,70",43,0
Sem Previsão,AL,Estrela de Alagoas,18306,"527.206,83",39,0
Sem Previsão,AM,Autazes,37033,"1.171.151,92",51,0
Sem Previsão,AM,Benjamin Constant,39484,"844.586,48",12,0
Concluída,AM,Coari,83078,"814.954,75",27,0
Concluída,AM,Manacapuru,94175,"892.096,87",31,"763.009,30"
Concluída,AM,Manaquiri,28413,"636.682,15",21,0
Concluída,AP,Serra do Navio,4938,"590.073,15",21,"495.899,00"
Concluída,BA,Guanambi,85797,"533.416,18",15,"441.985,58"
Em andamento,MG,Nepomuceno,26897,"650.576,00",27,0
Em andamento,PB,Cabaceiras,5449,"355.867,86",15,0
Em andamento,PB,Esperança,32785,"643.482,51",23,0
Em andamento,PB,Itaporanga,24499,"649.011,44",23,0
Em andamento,PR,Bandeirantes,32639,"279.409,70",7,0

In [70]:
cidadesUF_4 = cidadesDigitais.set_index(['STATUS', 'UF'])

In [71]:
cidadesUF_4.head(50)

                                    CIDADE  POPULAÇÃO VALOR_TOTAL_PREVISTO  \
STATUS       UF
Sem Previsão AC                   Tarauacá      38819           484.547,53
             AL            Delmiro Gouveia      51997         1.169.381,70
             AL         Estrela de Alagoas      18306           527.206,83
             AM                    Autazes      37033         1.171.151,92
             AM          Benjamin Constant      39484           844.586,48
             AM                    Careiro      36435           748.797,08
Concluída    AM                      Coari      83078           814.954,75
Sem Previsão AM                    Codajás      26777           757.706,74
             AM                   Iranduba      45984           800.655,02
Concluída    AM                 Manacapuru      94175           892.096,87
             AM                  Manaquiri      28413           636.682,15
Sem Previsão AM                      Maraã      18423           427.516,78
             AP                      Amapá       8622           459.240,58
             AP           Laranjal do Jari      45712           896.578,06
             AP                    Mazagão      19571           594.149,70
             AP               Porto Grande      19669           800.403,50
Concluída    AP             Serra do Navio       4938           590.073,15
Sem Previsão AP            Vitória do Jari      14364           687.756,22
             BA                      Abaré      19574           490.227,43
             BA                      Anagé      20096           510.328,56
             BA                    Anguera      11299           441.915,04
             BA                Baianópolis      14195           499.499,12
             BA                      Barra      54188         1.210.503,86
             BA             Barra do Choça      34853           747.990,32
             BA         Boa Vista do Tupim      18658           548.582,05
             BA         Bom Jesus da Serra      10554           413.597,59
             BA                Brejolândia      10698           437.370,14
             BA                 Buritirama      21549           486.364,54
             BA            Coronel João Sá      17098           623.361,08
             BA                   Cotegipe      14403           687.927,70
             BA                     Curaçá      35208           544.494,05
             BA               Encruzilhada      20331           401.380,67
Concluída    BA                   Guanambi      85797           533.416,18
Sem Previsão BA                 Guaratinga      22355           464.626,92
Concluída    BA                  Itaberaba      66310           533.277,38
             BA                    Itabuna     219680           623.601,85
Sem Previsão BA                  Jeremoabo      41100           703.108,89
Concluída    BA                   Juazeiro     218324           330.262,76
             BA           Lauro de Freitas     191436           710.505,26
             BA               Nilo Peçanha      14188           467.642,09
Sem Previsão BA            Pedro Alexandre      18135           584.854,35
             BA                      Piatã      18473           480.760,30
Concluída    BA             Piraí do Norte      10360           433.787,98
Sem Previsão BA  Presidente Tancredo Neves      27505           553.392,15
             BA            Rafael Jambeiro      24349           441.036,02
             BA          Riacho de Santana       4278           678.170,45
             BA               Rio do Pires      12084           473.521,57
             BA       Santa Rita de Cássia      28822           674.932,84
             BA              São Desidério      32640           674.932,84
Concluída    BA                    Uruçuca      21849           674.090,96

                 PONTOS_ATENDIDOS VALOR_INVESTIDO
STATUS       UF
Sem Previsão AC                 8               0
             AL                43               0
             AL                39               0
             AM                51               0
             AM                12               0
             AM                17               0
Concluída    AM                27               0
Sem Previsão AM                36               0
             AM                30               0
Concluída    AM                31      763.009,30
             AM                21               0
Sem Previsão AM                21               0
             AP                15               0
             AP                17               0
             AP                20               0
             AP                22       96.748,00
Concluída    AP                21      495.899,00
Sem Previsão AP                 7               0
             BA                23               0
             BA                15               0
             BA                20               0
             BA                24               0
             BA                46               0
             BA                23               0
             BA                28               0
             BA                16               0
             BA                17               0
             BA                20               0
             BA                27               0
             BA                36               0
             BA                13               0
             BA                17               0
Concluída    BA                15      441.985,58
Sem Previsão BA                17               0
Concluída    BA                16      409.445,98
             BA                17      463.707,87
Sem Previsão BA                15               0
Concluída    BA                 9      268.250,96
             BA                21      625.251,76
             BA                16      404.337,86
Sem Previsão BA                20               0
             BA                25               0
Concluída    BA                15      377.520,78
Sem Previsão BA                26               0
             BA                27               0
             BA                33               0
             BA                16               0
             BA                17               0
             BA                38               0
Concluída    BA                27      606.169,36

In [76]:
cidadesUF_4 = cidadesDigitais.set_index(['UF', 'STATUS'])

In [78]:
cidadesUF_4 = cidadesUF_4.groupby(level = ['UF', 'STATUS'])

In [79]:
cidadesUF_4.sum()

                 POPULAÇÃO  PONTOS_ATENDIDOS
UF STATUS
AC Sem Previsão      38819                 8
AL Sem Previsão      70303                82
AM Concluída        205666                79
   Sem Previsão     204136               167
AP Concluída          4938                21
   Sem Previsão     107938                81
BA Concluída       1171174               155
   Sem Previsão     532445               559
CE Concluída        658927               218
   Sem Previsão     427514               370
DF Concluída         32148                15
ES Sem Previsão     122164                94
GO Sem Previsão     166045               168
MA Concluída        174267                13
   Sem Previsão     571514               566
MG Concluída         18579                16
   Em andamento      26897                27
   Sem Previsão     465789               533
MS Sem Previsão     118431                94
MT Sem Previsão      77241                97
PA Concluída        620301               189
   Sem Previsão     470578               435
PB Concluída        127879                95
   Em andamento      62733                61
   Sem Previsão     111071               185
PE Concluída         37317                14
   Sem Previsão     342519               297
PI Concluída         37987                45
   Sem Previsão     187556               213
PR Concluída        418078               134
   Em andamento      32639                 7
   Sem Previsão     284252               247
RJ Concluída         13626                11
   Em andamento     167465                35
   Sem Previsão     413049               312
RN Concluída          6218                13
   Sem Previsão      77814               145
RO Sem Previsão      84470                39
RR Sem Previsão      27288                21
RS Concluída        107356                73
   Em andamento      40954                30
   Sem Previsão     300041               265
SC Concluída         29008                18
   Sem Previsão     187416                90
SE Sem Previsão     187455               107
SP Concluída        235299               173
   Em andamento      62857                37
   Sem Previsão     898779               810
TO Sem Previsão     117504               139

In [81]:
cidadesUF_4.aggregate(np.sum)

                 POPULAÇÃO  PONTOS_ATENDIDOS
UF STATUS
AC Sem Previsão      38819                 8
AL Sem Previsão      70303                82
AM Concluída        205666                79
   Sem Previsão     204136               167
AP Concluída          4938                21
   Sem Previsão     107938                81
BA Concluída       1171174               155
   Sem Previsão     532445               559
CE Concluída        658927               218
   Sem Previsão     427514               370
DF Concluída         32148                15
ES Sem Previsão     122164                94
GO Sem Previsão     166045               168
MA Concluída        174267                13
   Sem Previsão     571514               566
MG Concluída         18579                16
   Em andamento      26897                27
   Sem Previsão     465789               533
MS Sem Previsão     118431                94
MT Sem Previsão      77241                97
PA Concluída        620301               189
   Sem Previsão     470578               435
PB Concluída        127879                95
   Em andamento      62733                61
   Sem Previsão     111071               185
PE Concluída         37317                14
   Sem Previsão     342519               297
PI Concluída         37987                45
   Sem Previsão     187556               213
PR Concluída        418078               134
   Em andamento      32639                 7
   Sem Previsão     284252               247
RJ Concluída         13626                11
   Em andamento     167465                35
   Sem Previsão     413049               312
RN Concluída          6218                13
   Sem Previsão      77814               145
RO Sem Previsão      84470                39
RR Sem Previsão      27288                21
RS Concluída        107356                73
   Em andamento      40954                30
   Sem Previsão     300041               265
SC Concluída         29008                18
   Sem Previsão     187416                90
SE Sem Previsão     187455               107
SP Concluída        235299               173
   Em andamento      62857                37
   Sem Previsão     898779               810
TO Sem Previsão     117504               139

In [82]:
cidadesUF_4.aggregate([np.sum, np.mean, np.size])

                POPULAÇÃO                     PONTOS_ATENDIDOS
                      sum           mean size              sum       mean size
UF STATUS
AC Sem Previsão     38819   38819.000000    1                8   8.000000    1
AL Sem Previsão     70303   35151.500000    2               82  41.000000    2
AM Concluída       205666   68555.333333    3               79  26.333333    3
   Sem Previsão    204136   34022.666667    6              167  27.833333    6
AP Concluída         4938    4938.000000    1               21  21.000000    1
   Sem Previsão    107938   21587.600000    5               81  16.200000    5
BA Concluída      1171174  130130.444444    9              155  17.222222    9
   Sem Previsão    532445   22185.208333   24              559  23.291667   24
CE Concluída       658927   59902.454545   11              218  19.818182   11
   Sem Previsão    427514   28500.933333   15              370  24.666667   15
DF Concluída        32148   32148.000000    1               15  15.000000    1
ES Sem Previsão    122164   30541.000000    4               94  23.500000    4
GO Sem Previsão    166045   16604.500000   10              168  16.800000   10
MA Concluída       174267  174267.000000    1               13  13.000000    1
   Sem Previsão    571514   22860.560000   25              566  22.640000   25
MG Concluída        18579    9289.500000    2               16   8.000000    2
   Em andamento     26897   26897.000000    1               27  27.000000    1
   Sem Previsão    465789   18631.560000   25              533  21.320000   25
MS Sem Previsão    118431   39477.000000    3               94  31.333333    3
MT Sem Previsão     77241   19310.250000    4               97  24.250000    4
PA Concluída       620301   68922.333333    9              189  21.000000    9
   Sem Previsão    470578   31371.866667   15              435  29.000000   15
PB Concluída       127879   21313.166667    6               95  15.833333    6
   Em andamento     62733   20911.000000    3               61  20.333333    3
   Sem Previsão    111071   12341.222222    9              185  20.555556    9
PE Concluída        37317   37317.000000    1               14  14.000000    1
   Sem Previsão    342519   22834.600000   15              297  19.800000   15
PI Concluída        37987   12662.333333    3               45  15.000000    3
   Sem Previsão    187556   12503.733333   15              213  14.200000   15
PR Concluída       418078   59725.428571    7              134  19.142857    7
   Em andamento     32639   32639.000000    1                7   7.000000    1
   Sem Previsão    284252   31583.555556    9              247  27.444444    9
RJ Concluída        13626   13626.000000    1               11  11.000000    1
   Em andamento    167465   83732.500000    2               35  17.500000    2
   Sem Previsão    413049   34420.750000   12              312  26.000000   12
RN Concluída         6218    6218.000000    1               13  13.000000    1
   Sem Previsão     77814    9726.750000    8              145  18.125000    8
RO Sem Previsão     84470   42235.000000    2               39  19.500000    2
RR Sem Previsão     27288   27288.000000    1               21  21.000000    1
RS Concluída       107356   26839.000000    4               73  18.250000    4
   Em andamento     40954   20477.000000    2               30  15.000000    2
   Sem Previsão    300041   30004.100000   10              265  26.500000   10
SC Concluída        29008   29008.000000    1               18  18.000000    1
   Sem Previsão    187416   37483.200000    5               90  18.000000    5
SE Sem Previsão    187455   46863.750000    4              107  26.750000    4
SP Concluída       235299   29412.375000    8              173  21.625000    8
   Em andamento     62857   31428.500000    2               37  18.500000    2
   Sem Previsão    898779   35951.160000   25              810  32.400000   25
TO Sem Previsão    117504   29376.000000    4              139  34.750000    4

In [83]:
cidadesUF_5 = cidadesDigitais.set_index(['STATUS', 'CIDADE', 'VALOR_TOTAL_PREVISTO', 'VALOR_INVESTIDO', 'POPULAÇÃO'])

In [84]:
cidadesUF_5 = cidadesUF_5.groupby(level = ['STATUS', 'VALOR_TOTAL_PREVISTO', 'VALOR_INVESTIDO'])

In [85]:
cidadesDigitais.head(3)

,UF,CIDADE,POPULAÇÃO,VALOR_TOTAL_PREVISTO,STATUS,PONTOS_ATENDIDOS,VALOR_INVESTIDO
0,AC,Tarauacá,38819,"484.547,53",Sem Previsão,8,0
1,AL,Delmiro Gouveia,51997,"1.169.381,70",Sem Previsão,43,0
2,AL,Estrela de Alagoas,18306,"527.206,83",Sem Previsão,39,0

In [92]:
cidadesUF_5.sum().head(100)

                                                   PONTOS_ATENDIDOS
STATUS       VALOR_TOTAL_PREVISTO VALOR_INVESTIDO
Concluída    1.023.839,75         836.808,10                     34
             1.024.440,40         958.295,60                     35
             234.752,50           189.134,16                      5
                                  621.943,90                     24
             266.802,12           206.113,40                      6
...                                                             ...
Sem Previsão 1.116.548,04         0                              28
             1.119.305,92         0                              26
             1.120.514,49         92.707,50                      30
             1.132.841,73         0                              14
             1.135.692,68         0                              39

[100 rows x 1 columns]